Product:
  type: entity
  table: user_karma
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
    plus:
      type: integer
    minus:
      type: integer